{"level":"info","time":"2025-04-08T15:42:58.362+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/db/mysql.go:16","msg":"Init Mysql","serviceName":"pledge"}
{"level":"panic","time":"2025-04-08T15:42:58.370+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/db/mysql.go:37","msg":"mysql connention error ==>  dial tcp [::1]:33009: connectex: No connection could be made because the target machine actively refused it.","serviceName":"pledge"}
{"level":"info","time":"2025-04-08T15:44:09.777+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/db/mysql.go:16","msg":"Init Mysql","serviceName":"pledge"}
{"level":"panic","time":"2025-04-08T15:44:09.784+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/db/mysql.go:37","msg":"mysql connention error ==>  dial tcp [::1]:33009: connectex: No connection could be made because the target machine actively refused it.","serviceName":"pledge"}
{"level":"info","time":"2025-04-08T15:52:24.973+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/db/mysql.go:16","msg":"Init Mysql","serviceName":"pledge"}
{"level":"info","time":"2025-04-08T15:52:24.981+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/db/redis.go:15","msg":"Init Redis","serviceName":"pledge"}
{"level":"info","time":"2025-04-08T16:02:01.780+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/db/mysql.go:16","msg":"Init Mysql","serviceName":"pledge"}
{"level":"info","time":"2025-04-08T16:02:01.790+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/db/redis.go:15","msg":"Init Redis","serviceName":"pledge"}
{"level":"info","time":"2025-04-08T16:02:23.491+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/db/redis.go:15","msg":"Init Redis","serviceName":"pledge"}
{"level":"info","time":"2025-04-08T16:03:15.184+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/db/mysql.go:16","msg":"Init Mysql","serviceName":"pledge"}
{"level":"info","time":"2025-04-08T16:03:15.193+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/db/redis.go:16","msg":"Init Redis","serviceName":"pledge"}
{"level":"info","time":"2025-04-08T16:03:15.687+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/api/models/ws/ws.go:130","msg":"WsServer start","serviceName":"pledge"}
{"level":"info","time":"2025-04-08T16:03:15.687+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/api/models/kucoin/kucoin.go:23","msg":"GetExchangePrice ","serviceName":"pledge"}
{"level":"error","time":"2025-04-08T16:03:15.689+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/api/models/kucoin/kucoin.go:30","msg":"get plgr price from redis err redigo: nil returned","serviceName":"pledge"}
{"level":"error","time":"2025-04-08T16:03:36.756+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/api/models/kucoin/kucoin.go:45","msg":"Post \"https://api.kucoin.com/api/v1/bullet-public\": dial tcp 104.244.46.208:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","serviceName":"pledge"}
{"level":"info","time":"2025-04-08T16:04:13.590+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/db/mysql.go:16","msg":"Init Mysql","serviceName":"pledge"}
{"level":"info","time":"2025-04-08T16:04:13.598+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/db/redis.go:16","msg":"Init Redis","serviceName":"pledge"}
{"level":"error","time":"2025-04-08T16:04:13.849+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/schedule/common/common.go:16","msg":"environment variable is not set","serviceName":"pledge"}
{"level":"info","time":"2025-04-08T16:09:54.319+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/db/mysql.go:16","msg":"Init Mysql","serviceName":"pledge"}
{"level":"info","time":"2025-04-08T16:09:54.329+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/db/redis.go:16","msg":"Init Redis","serviceName":"pledge"}
{"level":"info","time":"2025-04-08T16:09:54.389+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/schedule/services/poolService.go:42","msg":"UpdatePoolInfo 0x216f718A983FCCb462b338FA9c60f2A89199490c https://data-seed-prebsc-1-s1.binance.org:8545","serviceName":"pledge"}
{"level":"error","time":"2025-04-08T16:10:57.536+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/schedule/services/poolService.go:65","msg":"Post \"https://data-seed-prebsc-1-s1.binance.org:8545\": dial tcp 157.240.17.35:8545: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","serviceName":"pledge"}
{"level":"error","time":"2025-04-08T16:11:18.596+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/schedule/services/tokenPriceService.go:134","msg":"Post \"https://data-seed-prebsc-1-s1.binance.org:8545\": dial tcp 31.13.80.169:8545: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","serviceName":"pledge"}
{"level":"error","time":"2025-04-08T16:11:18.597+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/schedule/services/tokenPriceService.go:70","msg":"UpdateContractPrice err DAI97Post \"https://data-seed-prebsc-1-s1.binance.org:8545\": dial tcp 31.13.80.169:8545: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","serviceName":"pledge"}
{"level":"error","time":"2025-04-08T16:11:39.644+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/schedule/services/tokenPriceService.go:134","msg":"Post \"https://data-seed-prebsc-1-s1.binance.org:8545\": dial tcp 31.13.80.169:8545: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","serviceName":"pledge"}
{"level":"error","time":"2025-04-08T16:11:39.647+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/schedule/services/tokenPriceService.go:70","msg":"UpdateContractPrice err BUSD97Post \"https://data-seed-prebsc-1-s1.binance.org:8545\": dial tcp 31.13.80.169:8545: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","serviceName":"pledge"}
{"level":"error","time":"2025-04-08T16:12:00.700+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/schedule/services/tokenPriceService.go:134","msg":"Post \"https://data-seed-prebsc-1-s1.binance.org:8545\": dial tcp 31.13.80.169:8545: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","serviceName":"pledge"}
{"level":"error","time":"2025-04-08T16:12:00.704+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/schedule/services/tokenPriceService.go:70","msg":"UpdateContractPrice err BTC97Post \"https://data-seed-prebsc-1-s1.binance.org:8545\": dial tcp 31.13.80.169:8545: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","serviceName":"pledge"}
{"level":"error","time":"2025-04-08T16:12:21.762+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/schedule/services/tokenPriceService.go:134","msg":"Post \"https://data-seed-prebsc-1-s1.binance.org:8545\": dial tcp 31.13.80.169:8545: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","serviceName":"pledge"}
{"level":"error","time":"2025-04-08T16:12:21.764+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/schedule/services/tokenPriceService.go:70","msg":"UpdateContractPrice err CAKE97Post \"https://data-seed-prebsc-1-s1.binance.org:8545\": dial tcp 31.13.80.169:8545: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","serviceName":"pledge"}
{"level":"error","time":"2025-04-08T16:12:43.383+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/schedule/services/tokenPriceService.go:134","msg":"Post \"https://data-seed-prebsc-1-s1.binance.org:8545\": dial tcp 31.13.67.41:8545: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","serviceName":"pledge"}
{"level":"error","time":"2025-04-08T16:12:43.384+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/schedule/services/tokenPriceService.go:70","msg":"UpdateContractPrice err BNB97Post \"https://data-seed-prebsc-1-s1.binance.org:8545\": dial tcp 31.13.67.41:8545: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","serviceName":"pledge"}
{"level":"error","time":"2025-04-08T16:13:04.465+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/schedule/services/tokenSymbolService.go:209","msg":"GetContractSymbolOnMainNet err 0x490BC3FCc845d37C1686044Cd2d6589585DE9B8BPost \"https://data-seed-prebsc-1-s1.binance.org:8545\": dial tcp 31.13.67.41:8545: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","serviceName":"pledge"}
{"level":"error","time":"2025-04-08T16:13:04.467+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/schedule/services/tokenSymbolService.go:61","msg":"UpdateContractSymbol err DAI97Post \"https://data-seed-prebsc-1-s1.binance.org:8545\": dial tcp 31.13.67.41:8545: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","serviceName":"pledge"}
{"level":"error","time":"2025-04-08T16:13:25.515+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/schedule/services/tokenSymbolService.go:209","msg":"GetContractSymbolOnMainNet err 0xE676Dcd74f44023b95E0E2C6436C97991A7497DAPost \"https://data-seed-prebsc-1-s1.binance.org:8545\": dial tcp 31.13.67.41:8545: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","serviceName":"pledge"}
{"level":"error","time":"2025-04-08T16:13:25.516+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/schedule/services/tokenSymbolService.go:61","msg":"UpdateContractSymbol err BUSD97Post \"https://data-seed-prebsc-1-s1.binance.org:8545\": dial tcp 31.13.67.41:8545: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","serviceName":"pledge"}
{"level":"error","time":"2025-04-08T16:13:46.566+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/schedule/services/tokenSymbolService.go:209","msg":"GetContractSymbolOnMainNet err 0xB5514a4FA9dDBb48C3DE215Bc9e52d9fCe2D8658Post \"https://data-seed-prebsc-1-s1.binance.org:8545\": dial tcp 31.13.80.169:8545: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","serviceName":"pledge"}
{"level":"error","time":"2025-04-08T16:13:46.567+0800","line":"C:/Users/Administrator/Documents/Project/github/openWeb3/Level3/Pledge/backend/schedule/services/tokenSymbolService.go:61","msg":"UpdateContractSymbol err BTC97Post \"https://data-seed-prebsc-1-s1.binance.org:8545\": dial tcp 31.13.80.169:8545: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.","serviceName":"pledge"}
